---

- name: Configure Arista VLAN's 
  hosts: arista
  tasks: 
    
    - name: create vlan 777
      eos_vlan: name=VLAN777 vlanid=777
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https



    - name: create vlan 778
      eos_vlan: name=VLAN778 vlanid=778
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: create vlan 779
      eos_vlan: name=VLAN779 vlanid=779
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

