---


- name: Exercise4 
  hosts: arista
  
  tasks: 
    - name: Make Ethernet3 access
      eos_switchport: name=Ethernet3 mode=access access_vlan=1 trunk_allowed_vlans=1-4094
         username={{ eapi_username }}
         password={{ eapi_password }}
         host={{ eapi_hostname }}
         port={{ eapi_port }}
         transport=https

    - name: Change Description
      eos_interface: name=Ethernet3 description="" 
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https 

    - name: Remove vlans
      eos_vlan: vlanid={{ item }} state=absent
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https

      with_items:
         - 777
         - 778
         - 779
