---

- name: Trunk Configuration exercise
  hosts: arista
  tasks:
    - name: Trunk modification
      eos_switchport: name=Ethernet3 mode=trunk trunk_native_vlan=1 trunk_allowed_vlans=777,778,779
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https


