---

- name: Configure Primary Interface
  hosts: arista
  tasks:

   - name: Add description and vlans to port
     eos_interface: name=Ethernet3 description="*** TESTING ***"
         username={{ eapi_username }}
         password={{ eapi_password }}
         host={{ eapi_hostname }}
         port={{ eapi_port }}
         transport=https

   - name: Change mode to access
     eos_switchport: name=Ethernet3 mode=access access_vlan=777
         username={{ eapi_username }}
         password={{ eapi_password }}
         host={{ eapi_hostname }}
         port={{ eapi_port }}
         transport=https

 
